import { Injectable } from '@nestjs/common'
import { randomUUID } from 'crypto'
import { createReadStream, existsSync } from 'fs'
import { mkdir, rm, writeFile } from 'fs/promises'
import { dirname, join, resolve } from 'path'
import type { Readable } from 'stream'
import { config } from '../config'

/**
 * Where uploaded bytes live. v1 uses LocalStorageService (disk); an S3/R2
 * implementation can replace it later without touching callers.
 */
export abstract class StorageService {
  /** Stores the bytes and returns an opaque storage key. */
  abstract save(data: Buffer, ext: string): Promise<string>
  abstract open(key: string): Readable
  abstract exists(key: string): boolean
  abstract remove(key: string): Promise<void>
}

@Injectable()
export class LocalStorageService extends StorageService {
  private get root() {
    return resolve(config().UPLOAD_DIR)
  }

  private pathFor(key: string) {
    // Keys are generated by us (date folders + UUID) — still refuse anything that escapes the root.
    const full = resolve(join(this.root, key))
    if (!full.startsWith(this.root)) throw new Error('Invalid storage key')
    return full
  }

  async save(data: Buffer, ext: string): Promise<string> {
    const now = new Date()
    const key = `${now.getUTCFullYear()}/${String(now.getUTCMonth() + 1).padStart(2, '0')}/${randomUUID()}.${ext}`
    const full = this.pathFor(key)
    await mkdir(dirname(full), { recursive: true })
    await writeFile(full, data)
    return key
  }

  open(key: string): Readable {
    return createReadStream(this.pathFor(key))
  }

  exists(key: string): boolean {
    return existsSync(this.pathFor(key))
  }

  async remove(key: string): Promise<void> {
    await rm(this.pathFor(key), { force: true })
  }
}
